export const animals = {
  avianAnimal: {
    avian: true,
    canine: false,
    earthAnimal: false,
    earthInsect: false,
    feline: false,
    name: 'avian',
    uid: 'avian_uid',
    checked: false,
  },
  canineAnimal: {
    avian: false,
    canine: true,
    earthAnimal: false,
    earthInsect: false,
    feline: false,
    name: 'canine',
    uid: 'canine_uid',
    checked: false,
  },
  earthAnimal: {
    avian: false,
    canine: false,
    earthAnimal: true,
    earthInsect: false,
    feline: false,
    name: 'earthAnimal',
    uid: 'earth_uid',
    checked: false,
  },

  earthInsect: {
    avian: false,
    canine: false,
    earthAnimal: false,
    earthInsect: true,
    feline: false,
    name: 'earthInsect',
    uid: 'earthInsect_uid',
    checked: false,
  },
  felineAnimal: {
    avian: false,
    canine: false,
    earthAnimal: false,
    earthInsect: false,
    feline: true,
    name: 'feline',
    uid: 'felin_uid',
    checked: false,
  },
  underfinedType: {
    avian: false,
    canine: false,
    earthAnimal: false,
    earthInsect: false,
    feline: false,
    name: 'underfinedType',
    uid: 'felin_uid',
    checked: false,
  },
};
